spring:
  application:
    name: moneylog

  datasource:
    url: jdbc:mysql://localhost:3306/moneylog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jinney0830!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: "qM6bK3z9PxVtY7uJr1FgNcT4sA0HdXeZ"
    expiration: 3600000

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  address: 0.0.0.0
  port: 8080

clova:
  ocr:
    url: https://gdbjtc0gwz.apigw.ntruss.com/custom/v1/45221/34ee005010756fc54dbef3500d9cd6102f8676c91a737099b2fde189db9bb3c5/document/receipt
    secret: UG9sa3ZTZk1OZWN5eGFEQnBHbUtHV1pOYUlMeGFaYmk=
