spring:
  application:
    name: moneylog

  datasource:
    url: jdbc:mysql://localhost:3306/moneylog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: jinney0830!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

clova:
  ocr:
    url: https://w8qj4x5lqf.apigw.ntruss.com/custom/v1/45023/aed44ca2a5c0d44b78eb174c1577634a9f06423babf963c84b57d29ebde234fc/general
    secret: WmJkUEtBamFxQllhd1BWQ3FGeFF4a29IUVFBUUdKYmY=