spring:
  application:
    name: moneylog

  datasource:
    url: jdbc:mysql://localhost:3306/moneylog?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 241122

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: "qM6bK3z9PxVtY7uJr1FgNcT4sA0HdXeZ"
    expiration: 3600000


  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

  task:
    scheduling:
      pool:
        size: 2

fcm:
  credentials: classpath:moneylog-36771-firebase-adminsdk-fbsvc-c2455008eb.json

server:
  address: 0.0.0.0
  port: 8080